language: python
matrix:
  include:
    - python:
        - "2.7"
    - python:
        - "3.3"
    - python:
        - "3.4"
    - python:
        - "3.5"
    - python:
        - "3.6"
    - python:
        - "3.7"
      dist: xenial
      services:
        - postgresql
install: pip install tox-travis tox flake8
sudo: false
script: tox
before_script:
  - flake8 django_migration_testcase tests --ignore=E501,E128,E402
  - psql -c 'create database migration_test;' -U postgres
